const {test,expect,_electron}=require('@playwright/test');
const path=require('node:path');
const {resetSession}=require('./session-helpers.cjs');
test('waveform selection, cancellation, reference ranges and time zoom',async()=>{
  resetSession();
  const app=await _electron.launch({args:[path.resolve(__dirname,'../..')],env:{...process.env,MQV_TEST_PROFILE:'1',ELECTRON_DISABLE_SECURITY_WARNINGS:'true'}});
  try{
    const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));
    await expect(page.locator('#engine-status')).toContainText('Python',{timeout:30000});
    await page.evaluate(async()=>{sessionReady=false;const request=await api.demo();request.mode='mix';request.stems={};const r=await api.analyze(request);addResult(r,'target');addResult({...r,id:'wave-ref',name:'Wave REF'},'reference');});
    await page.locator('#range-waveform').click();
    await expect(page.locator('#waveform-status')).toContainText('元ステレオ',{timeout:30000});
    const box=await page.locator('#range-wave').boundingBox();
    const drag=async(a,b)=>{await page.mouse.move(box.x+20+(box.width-40)*a,box.y+100);await page.mouse.down();await page.mouse.move(box.x+20+(box.width-40)*b,box.y+100,{steps:10});await page.mouse.up();};
    await drag(.2,.6);
    let selected=await page.evaluate(()=>[...waveEditor.range]);
    const total=await page.evaluate(()=>state.target.duration);
    expect(selected[0]).toBeCloseTo(total*.2,1);expect(selected[1]).toBeCloseTo(total*.6,1);
    await drag(.6,.75);await drag(.4,.5);
    selected=await page.evaluate(()=>[...waveEditor.range]);
    expect(selected[0]).toBeCloseTo(total*.3,1);expect(selected[1]).toBeCloseTo(total*.85,1);
    await page.screenshot({path:'test-results/waveform-selection.png'});
    await page.locator('#wave-cancel').click();
    expect(await page.evaluate(()=>range(state.target))).toEqual([0,total]);
    await page.locator('#range-waveform').click();await expect(page.locator('#waveform-status')).toContainText('元ステレオ');
    await drag(.2,.8);await page.locator('#wave-apply').click();
    expect((await page.evaluate(()=>range(state.target)))[0]).toBeCloseTo(total*.2,1);
    await page.locator('[data-tab=references]').click();await page.locator('.reference-track').getByRole('button',{name:'波形で区間を選択'}).click();
    await expect(page.locator('#range-track-name')).toHaveText('Wave REF');
    await page.locator('#wave-start').fill('5');await page.locator('#wave-end').fill('4');await page.locator('#wave-apply').click();
    await expect(page.locator('#wave-error')).not.toBeEmpty();await expect(page.locator('#range-dialog')).toBeVisible();
    await page.locator('#wave-start').fill('1');await page.locator('#wave-end').fill('4');await page.locator('#wave-apply').click();
    expect(await page.evaluate(()=>state.ranges['wave-ref'])).toEqual([1,4]);
    await page.locator('[data-tab=density]').click();
    const original=await page.evaluate(()=>({range:range(state.target),stat:stat(state.target,'density_pct')}));
    const chart=await page.locator('#timeline').boundingBox();
    await page.mouse.move(chart.x+chart.width*.65,chart.y+80);await page.mouse.wheel(0,-600);
    await expect.poll(()=>page.evaluate(()=>chartView.end-chartView.start)).toBeLessThan(.5);
    const zoomed=await page.evaluate(()=>chartTimes(state.target));
    expect(await page.evaluate(()=>({range:range(state.target),stat:stat(state.target,'density_pct')}))).toEqual(original);
    await page.locator('#timeline').click({position:{x:48+(chart.width-60)*.5,y:80}});
    await expect.poll(()=>page.locator('#audio').evaluate(e=>e.currentTime)).toBeCloseTo((zoomed[0]+zoomed[1])/2,1);
    await page.screenshot({path:'test-results/timeline-zoom.png'});
    await page.locator('#chart-pan').fill('1');
    expect(await page.evaluate(()=>chartView.end)).toBeCloseTo(1);
    const heat=await page.locator('#heatmap').boundingBox();await page.locator('#heatmap').hover();await page.mouse.wheel(0,-300);
    await expect.poll(()=>page.evaluate(()=>chartView.end-chartView.start)).toBeLessThan(.3);
    await page.locator('#chart-reset').click();expect(await page.evaluate(()=>chartView.end-chartView.start)).toBe(1);
    await page.mouse.move(chart.x+chart.width*.5,chart.y+80);await page.mouse.wheel(0,600);
    expect(await page.evaluate(()=>chartView.end-chartView.start)).toBe(1);
    expect(errors).toEqual([]);
  }finally{await app.close();}
});
